/** @format */
//pages
export const MENU_BUTTON_1 = 'MENU_BUTTON_1'
export const MENU_BUTTON_2 = 'MENU_BUTTON_2'
export const MENU_BUTTON_3 = 'MENU_BUTTON_3'
export const CHANGE_PAGE_MESSAGE = 'CHANGE_PAGE_MESSAGE'
//permissions
    //set
export const SET_PERMISSION_PROFILE = 'SET_PERMISSION_PROFILE'
export const SET_PERMISSION_SWIPE = 'SET_PERMISSION_SWIPE'
export const SET_PERMISSION_MESSAGE = 'SET_PERMISSION_MESSAGE'
    //revoke
export const REVOKE_PERMISSION_PROFILE = 'REVOKE_PERMISSION_PROFILE'
export const REVOKE_PERMISSION_SWIPE = 'REVOKE_PERMISSION_SWIPE'
export const REVOKE_PERMISSION_MESSAGE = 'REVOKE_PERMISSION_MESSAGE'

//swipe
export const LOG_KISS = 'LOG_KISS'
export const LOG_MARRY = 'LOG_MARRY'
export const LOG_AVOID = 'LOG_AVOID'

//message
export const LOG_MESSAGE = 'LOG_MESSAGE'