/** @format */
//pages
export const CHANGE_PAGE_PROFILE = 'CHANGE_PAGE_PROFILE'
export const CHANGE_PAGE_SWIPE = 'CHANGE_PAGE_SWIPE'
export const CHANGE_PAGE_MESSAGES = 'CHANGE_PAGE_MESSAGES'
export const CHANGE_PAGE_MESSAGE = 'CHANGE_PAGE_MESSAGE'
//permissions
    //set
export const SET_PERMISSION_PROFILE = 'SET_PERMISSION_PROFILE'
export const SET_PERMISSION_SWIPE = 'SET_PERMISSION_SWIPE'
export const SET_PERMISSION_MESSAGE = 'SET_PERMISSION_MESSAGE'
    //revoke
export const REVOKE_PERMISSION_PROFILE = 'REVOKE_PERMISSION_PROFILE'
export const REVOKE_PERMISSION_SWIPE = 'REVOKE_PERMISSION_SWIPE'
export const REVOKE_PERMISSION_MESSAGE = 'REVOKE_PERMISSION_MESSAGE'
//swipe
export const LOG_KISS = 'LOG_KISS'
export const LOG_MARRY = 'LOG_MARRY'
export const LOG_AVOID = 'LOG_AVOID'