

export const placeholder = () => {
    return( `why not talk about... ${suggestion[suggestion.length * Math.random() | 0]}`)
};
export const forcedPlaceholder = (name: any) => {
    return `You need to message ${name}... Suggestion: ${suggestion[suggestion.length * Math.random() | 0]}`
 };

const suggestion = [
    'What show your binge-watching right now?',
    'If you could be anyone for one day, who would you be?',
    'What is your comfort food?',
    'food or sex, what would you choose?',
    'three things if you are stuck on a deserted island?',
    'prefer to read a book or watch a movie based on the book?',
    'describe yourself in one word?',
    'Would you rather be the most intelligent person in the world or the most beautiful?',
    'Which is your favorite Friends character?',
    'Was Ross on a break?',
    'Do you believe in love at first sight?',
    'What, according to you, is the most attractive quality?',
    'Do you prefer texting or calling?',
    'Have you ever been on a blind date?',
    'Are you a cat or a dog person?',
    'Have you ever been in love?',
    'What is the one thing you would want to change about yourself?',
    'What quality is the biggest turn-off for you?',
    'Which movie or TV character can you relate to the most?',
    'Would you rather sit and watch Netflix or party with friends?',
    'Would you rather//why not talk about... //suggestion... go on a relaxing vacation or an adventure?',
    'Are you an optimist or a cynic?',
    'If you had to choose between sleeping late and waking up early, what would you prefer?',
    'What is the craziest thing you have ever done?',
    'What is your best physical feature?',
    'What do you enjoy doing in your spare time?',
    'Who is the most important person in your life right now?',
    'What is your go-to song when you are sad?',
    'Which is your most preferred emoji?',
    'What are you passionate about?',
    'What is the weirdest place where you kissed?',
    'Are you an emotional or a practical person?',
    'What is your dream holiday destination?',
    'What is your hidden talent?',
    'Which is your favorite movie genre?',
    'What is your most annoying habit?',
    'Are you superstitious?',
    'Do you believe in karma?',
    'How many days can you go without your phone?',
    'Which is your favorite romcom?',
    'Do you have any phobias? What are they?',
    'If you can eat only one food item for a week, which one would you choose?',
    'When did you last go on a date?',
    'What is your idea of a perfect date?',
    'If today was your last day on earth, how would you spend it?',
    'Would you do something illegal to save your closest friend?',
    'Are you good at keeping secrets?',
    'What does your favorite breakfast look like?',
    'Do your close friends have a pet name for you? What is it?',
    'What is your negative attribute?',
    'Which is your favorite beverage?',
    'Which movie can you watch every day and still not get tired of?',
    'Which is your spirit animal?',
    'What is the best compliment you have ever received?',
    'What is the craziest wish on your bucket list?',
    'What is the one song you can’t help but sing along to every time you hear it?',
    'Which food best describes your personality?',
    'What is the scariest horror movie you have ever seen?',
    'What is the weirdest ice cream flavor you have ever tried?',
    'What is the last thing you searched on the internet?',
    'What is the first thing that people usually notice about you?',
    "Do you play any sport's?",
    'How would you rate your personality on a scale of 10?',
    'go-to pick-up line?',
    'Have you ever had a one-night stand?',
    'Which superhero would you want to be reincarnated as?',
    'Do you prefer outdoor games or video games?',
    'How would you describe your first kiss?',
    'Which is your favorite TV show of all time?',
    'What is the most precious thing you own?',
    'Do you believe in destiny?',
    'Do you have a go-to joke that you always tell people to make them laugh?',
    'Do you play any musical instruments?',
    'How old were you when you had your first crush?',
    'What genre of music do you enjoy listening to?',
    'What is your most preferred location for a first date?',
    'What is the stupidest thing you have ever said or done on a date?',
    'Who was your inspiration growing up?',
    'What made you interested in my profile?',
    'What is the most common misconception about you?',
    'Which is your favorite cuisine?',
    'Which year in your life would you describe as the golden period?',
    'Which actor is overrated, according to you?',
    'What is something you are dying to try but haven’t tried till now?',
    'Did you ever try skydiving?',
    'Have you ever trolled a celebrity on social media?',
    'What is your worst party experience?',
    'How would your friends describe you?',
    'When was your last date? How was it?',
    'What is the first thing you noticed about my profile picture?',
    'Which topic can you discuss for hours without getting tired or bored?',
    'Which is your favorite restaurant in the area?',
    'What is the most important thing for you in a relationship?',
    'Have you ever traveled outside the country? How many countries have you been to?',
    'How do you generally spend your weekends?',
    'Have you asked your friend to call and bail you out during a bad date?',
    'Which is the one thing you cannot live without?',
    'What is the worst dating advice you have ever received?',
    'How often do you work out?',
    'Do you lie on your CV?',
    'How do you like to celebrate your birthday?',
    'Do you enjoy watching rom-com or thriller movies?',
    'What activity brings a smile to your face when you are feeling sad?',
    'Do you believe in soulmates?',
    'What is the weirdest date you have ever had?',
    'If given a chance, which celebrity would you like to date?',
    'Are you a bibliophile?',
    'What kind of books do you read?',
    'Do you enjoy socializing, or are you reserved?',
    'Have you ever tried any weird food item? What was it?',
    'What is your biggest achievement in life?',
    'Which food item would you never have even if you were hungry?',
    'When did your last relationship end?',
    'Apart from love, what do you think is important in a relationship?',
    'What is your dream job?',
    'Are you a good karaoke singer?',
    'Do you think humans will ever inhabit Mars?',
    'What is the most terrifying experience of your life?',
    'If you were the writer of Game of Thrones, how would you end the series?',
    'Have you ever created a fake profile on social media?',
    'Would you rather quit alcohol for a year or turn vegan for a year?',
    'Would you rather never have pizza or have pizza with pineapple topping for a month?',
    'Have you ever tried to repair something and you worsened the situation?',
    'If you were to make a movie based on your life, what would you call it?',
    'What is the ridiculous story you have made up for being late for work?',
    'What is the stupidest thing you’ve ever done on a dare?',
    'Would you be rather caught with your clothes inside out or your shirt buttoned the wrong way?',
    'What is the most embarrassing thing you’ve ever done while you were drunk?',
    'What is the most ridiculous thing you have ever done as a child?',
    'What are you most likely to get arrested for?',
    'What is the most awkward experience of your life?',
    'Who is the funniest TV character, according to you?',
    'What is the silliest belief you had as a child?',
    'If you were a student of Hogwarts, which house would you be placed in?',
    'What is the biggest blunder you have made at work?',
    'Date the most irritating person you have ever met for a month or not date for a whole year?',
    'Where do you go on nights out?',
    "What's the best present you ever gave someone?",
    'Dogs or cats, which do you like?',
    "What's your weirdest quality?",
    'Are you a night owl or early bird?',
    'Top 3 Disney Movies',
    'dry humor or weird/goofy humor?',
    'If you could get free season tickets to sport, who would you choose? ',
    'If you had to spend $5 million in one day, how would you spend it?',
    "Worst movie you've ever seen?",
    'Concert or theater',
    'If you could only eat one type of donut for the rest of your life, what would it be?',
    'Sweet potato fries or onion rings?',
    'Do you sneak food into the movie theaters?',
    'What would you be famous for and why?',
    "What's your life story in 3 sentences?",
    'Your worst memory?',
    'What three things do you think we have in common?',
    'What are you most grateful for?',
    'What is one thing that is important for me to know about you?',
    'What is something you like about me already?',
    'Braveheart or Gladiator?',
    'Favorite inspirational quote?',
    'What do you order at brunch?',
    'What movie has made you cry?',
    'what do they fear most?',
    'Coffee or tea?',
    'Chandler or Ross? / Rachel or Monica?',
    "What's your happy music?",
    'Pandas or penguins?',
    'Salty or sweet?',
    'Do you believe in aliens?',
    'Do you believe in ghosts?',
    'What makes you feel unstoppable?',
    'What makes you feel super loved?',
    'What makes you feel most alive?',
    'When do you feel the most vulnerable?',
    'What do you think makes me smile?',
    'What annoys you the most about people in three words?',
    'Where would you like to be in five years?',
    'How would your best friends describe you?',
    'Do you usually follow your head or your heart?',
    'Where do you go when you need some inspiration?',
    'If a psychic with a crystal ball told you that you only had one year to live, what would you change in your life?',
    'Do you think confessions make a relationship stronger?',
    'What has been the best phase in your life thus far?',
    'If you could choose one superpower, what would it be and why?',
    'What is your favorite childhood memory about a favorite teacher?',
    'What do you do when you are angry?',
    'What is your biggest regret in life so far?',
    'What are your beliefs about God or a higher power?',
    'Do you believe that life after death is possible?',
    'What is your philosophy in life?',
    'If you were given three things to make you happy, what would these be?',
    'What makes you feel accomplished?',
    'What is a relationship deal-breaker for you?',
    'Do you consider yourself an introvert or an extrovert?',
    'Which parent are you closer to, and why?',
    'What lies do you most often tell yourself?',
    'What legacy do you want people to remember about you after you’re gone?',
    'Do you think the present is better than 50 years ago? Why?',
    'What advice would you give to the current younger generation?',
    'What is your idea of a perfect date?',
    'Which fictional character do you most relate to and why?',
    'Describe your ideal weekend.',
    'What’s a guilty pleasure that people always misunderstand about you?',
    'Would you rather take a trip to the beach, the mountains, or an amusement park?',
    "What is the craziest thing you've ever done?",
    'What is on your bucket list this year?',
    'When have you felt your biggest adrenaline rush?',
    'What is the craziest thing you’ve ever done, and would you do it again?',
]
